== Apiman Docker Compose Quickstart Distro

This Apiman Docker Compose quickstart distro allows you to try out Apiman an architecture that is more representative of a real-world deployment.

Please ensure you change any default passwords before going to production.

If you have feedback, please leave it on https://github.com/apiman/apiman/discussions[Apiman Discussions^] on GitHub.

Main Apiman repo: https://www.github.com/apiman/apiman

Apiman Docker repo: https://www.github.com/apiman/apiman-docker

=== Getting running

* Initialise secrets and keys: `./setup.sh`.
** This should be run *before* starting docker-compose.
** We will generate self-signed RSA certificates for you to use in Keycloak.
+
The default keysize is 2048 bits. Set the `RSA_KEY_SIZE` environment variable
before running `setup.sh` if you want a different keysize.
+
These are also copied into `.env`, where they can be injected into Apiman, etc.

* Start docker compose: `docker-compose up` or `docker compose up`
* Location of services:
** Apiman Manager UI: `http://localhost:8080/apimanui`
** Apiman Manager API: `http://localhost:8080/apiman`
** Apiman Gateway: `http://localhost:8080/gateway`
** Apiman Gateway API: `http://localhost:8080/gateway-management`
** Keycloak Admin: `http://localhost:8080/auth/admin`
** Keycloak Auth Endpoint: `http://localhost:8080/auth`
** Elasticsearch: `http://localhost:8080/elasticsearch`

* Default user and password for Apiman and Keycloak Admin:
** Username: `admin`
** Password: `admin123!`

=== Production notes

==== Apiman

* Assuming you are terminating TLS/SSL on Apiman, the demo self-signed certificates, keystores, truststores, etc, should be replaced with your organisation's versions.

* Components for such as Postgres and Elasticsearch likely should be run in a multi-node setup to provide high levels of resilience and redundancy.
You should make some considerations for backups, etc.

==== Keycloak

* For a real deployment, please run Keycloak in production mode. For this quickstart it runs in dev-mode, which is very permissive and tolerant of self-signed certs, etc -- but it is inappropriate for real-world deployments. https://www.keycloak.org/server/configuration-production[Refer to the Keycloak production guide^].

* You **must** change the default usernames and/or passwords before going to production.

* Keys are generated and stored in `data/keys`, and then copied into the `.env` file.
Storing keys in plaintext is not usually advised for a production environment; you should consider using a dedicated secrets storage and injection mechanism. For example, Hashicorp Vault or K8s secrets.


