name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-verify:
    name: Verify Docker Image Builds
    runs-on: ubuntu-latest
    if: github.repository_owner == 'Apiman'
    env:
      APIMAN_RELEASE_VERION: 2.1.0.Final
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker images
        run: |
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/cli:latest cli
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/on-wildfly:latest on-wildfly
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-openshift:latest vertx-openshift
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-standalone:latest vertx-standalone
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-gateway:latest vertx-gateway
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/migration-assistant:latest migration-assistant
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/wildfly-manager:latest wildfly-manager
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/tomcat-manager:latest tomcat-manager

  publish-latest:
    name: Publish Docker Latest Images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'Apiman'
    needs: [ build-verify ]
    env:
      APIMAN_RELEASE_VERION: 2.1.0.Final
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker images
        run: |
          # apiman/on-wildfly:latest is build and pushed via main pipeline
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/cli:latest -t ghcr.io/apiman/cli:latest cli
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-openshift:latest -t ghcr.io/apiman/vertx-openshift:latest vertx-openshift
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-standalone:latest -t ghcr.io/apiman/vertx-standalone:latest vertx-standalone
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/vertx-gateway:latest -t ghcr.io/apiman/vertx-gateway:latest vertx-gateway
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/migration-assistant:latest -t ghcr.io/apiman/migration-assistant:latest migration-assistant
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/wildfly-manager:latest -t ghcr.io/apiman/wildfly-manager:latest wildfly-manager
          docker build --build-arg "APIMAN_VERSION=${{ env.APIMAN_RELEASE_VERION }}" -t apiman/tomcat-manager:latest -t ghcr.io/apiman/tomcat-manager:latest tomcat-manager

          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          # apiman/migration-assistant:latest is only pushed to ghcr.io
          docker push apiman/cli:latest
          docker push apiman/vertx-openshift:latest
          docker push apiman/vertx-standalone:latest
          docker push apiman/vertx-gateway:latest
          docker push apiman/wildfly-manager:latest
          docker push apiman/tomcat-manager:latest

          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/apiman/cli:latest
          docker push ghcr.io/apiman/vertx-openshift:latest
          docker push ghcr.io/apiman/vertx-standalone:latest
          docker push ghcr.io/apiman/vertx-gateway:latest
          docker push ghcr.io/apiman/migration-assistant:latest
          docker push ghcr.io/apiman/wildfly-manager:latest
          docker push ghcr.io/apiman/tomcat-manager:latest
