name: Docker PR CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Get release and snapshot versions..."
        run: |
          echo "{release_version=$(cat .github/workflows/RELEASE_VERSION)}" >> $GITHUB_ENV
          echo "{snapshot_version=$(cat .github/workflows/SNAPSHOT_VERSION)}" >> $GITHUB_ENV

      - name: "Build & verify PR against Apiman release ${{ env.release_version }}"
        uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
        with:
          apiman-version: ${{ env.release_version }}
          push-to-repos: false
          snapshot: false
          
      - name: "Build & verify PR against Apiman snapshot ${{ env.snapshot_version }}"
        uses: apiman/apiman-docker/.github/workflows/docker-test-release.yml@master
        with:
          apiman-version: ${{ env.snapshot_version }}
          push-to-repos: false
          snapshot: true
