name: update Apiman release version & trigger release

on:
  repository_dispatch:
    types:
      - apiman-release-version
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Apiman Docker repo
        uses: actions/checkout@v3

      - name: Default setup items
        run: bash .git/workflows/support/setup.sh

      - name: Update release version in docker-release flow
        run: echo ${{ github.event.client_payload.release-version }} > .github/workflows/RELEASE_VERSION

      - name: Commit release version update to repository
        uses: EndBug/add-and-commit@v7.2.1
        with:
          author_name: apiman-ci
          default_author: user_info
          message: "chore(ci): update RELEASE_VERSION to ${{ github.event.client_payload.release-version }}"
          add: .github/workflows --force
